export const database = 
    [
        { condition: "new", category: "album", title: "토끼와 거북이", url: "/images/family/202310251600_son_토끼와 거북이.jpeg" },

        
        { category: "album", title: "주간 장하성 13주차", url: "/images/family/2022123100_son_13주차 장하성.JPG" },
        { category: "album", title: "인생에 공짜란 없다", url: "/images/family/2023091300_son_인생에 공짜란 없다.JPG" },
        { category: "album", title: "우주 애기", url: "/images/family/202310211400_son_우주애기.JPG" },
        { category: "album", title: "장아련 투", url: "/images/family/202310211402_son_아련하다.JPG" },
        { category: "album", title: "아빠 팬티가 좋아요.", url: "/images/family/202310211403_son_아빠팬티가 좋아요.JPG" },
        { category: "album", title: "작곡가 하성", url: "/images/family/202310231100_son_작곡가 하성.jpeg" },
        { category: "album", title: "스티커가 좋아요", url: "/images/family/202310241100_son_스티커가 좋아요.jpeg" },
        { category: "album", title: "주간 장하성 5주차", url: "/images/family/202212021200_son_주간 장하성 5주차.JPG" },
        { category: "album", title: "주간 장하성 2주차", url: "/images/family/202210091900_son_주간장하성2주차.JPG" },
        { category: "album", title: "주간 장하성 3주차", url: "/images/family/202210202200_son_장하성 3주차.jpg" },
        { category: "album", title: "돌_ 미미치치는 무서워", url: "/images/family/202310051800_son_미미치치는 무서워.JPG" },
        { category: "album", title: "아빠 닮은 하성", url: "/images/family/202310181700_son_아빠와 닮은 하성.jpeg" },
        { category: "album", title: "만세 하성", url: "/images/family/202310191100_son_만세 하성.jpeg" },
        { category: "album", title: "잠하성", url: "/images/family/202310201200_son_잠하성.JPG" },
        { category: "album", title: "귀염둥이 장또순, 째려봄", url: "/images/dog/2021_귀염둥이 장또순 네번째.jpeg" },
        { category: "album", title: "토토로의 빗자루, 해군의 배", url: "/images/family/202310150900_son_토토로의 빗자루와 해군의 배.JPG" },
        { category: "album", title: "토마토 빗자루를 잡은 아들", url: "/images/family/202310150901_son_토토로의 빗자루를 잡은 아들.JPG" },
        { category: "album", title: "나무가 좋아욤...", url: "/images/family/202310150904_son_나무가 좋아요.JPG" },
        { category: "album", title: "생각하는 하성 츄츄", url: "/images/family/202310150905_son_생각하는 하성츄츄.JPG" },
        { category: "album", title: "도발하는 하성", url: "/images/family/202310150906_son_도발하는 하성.JPG" },
        { category: "album", title: "피아노 앞의 하성", url: "/images/family/202310150907_son_피아노 앞의 하성.JPG" },
        { category: "album", title: "피아노 치는 하성", url: "/images/family/202310150907_son_피아노치는 하성.JPG" },
        { category: "album", title: "돌_ 미미치치는 무섭다", url: "/images/family/202310051800_son_돌_미미치치는 무섭다.JPG" },
        { category: "album", title: "돌_ 친가 식구들", url: "/images/family/202310051801_family_돌_친가 식구들.JPG" },
        { category: "album", title: "돌_ 전체 식구들", url: "/images/family/202310051802_family_돌_전체 식구들.JPG" },
        { category: "album", title: "돌_ 외가 식구들", url: "/images/family/202310051803_family_돌_외가 식구들.JPG" },
        { category: "album", title: "돌_ 박수치는 장하성", url: "/images/family/202310051804_family_돌_박수치는 장하성.JPG" },
        { category: "album", title: "돌_ 장하성의 선택", url: "/images/family/202310051805_family_돌_장하성의 선택.JPG" },
        { category: "album", title: "돌_ 상수리 나무 아래서", url: "/images/family/202310051806_family_돌_상수리나무아래서.JPG" },
        { category: "album", title: "돌_ 가족의 인사", url: "/images/family/202310051807_family_돌_가족의 인사.gif" },
        { category: "album", title: "토마토의 취침", url: "/images/family/202310101200_son_토마토의 취침.JPG" },
        { category: "album", title: "장난감 천재 장하성", url: "/images/family/202310101000_son_장난감을 좋아하는 하성.JPG" },
        { category: "album", title: "엄마와 장하성", url: "/images/family/20230910_son_mother_프로필사진.jpeg" },
        { category: "album", title: "교회에서 졸린 장아련", url: "/images/family/202310081200_son_교회에서 졸린 장하성.jpeg" },
        { category: "album", title: "성남 놀러간 아들", url: "/images/family/202310081500_son_성남 놀러간 아들.jpeg" },
        { category: "album", title: "장아련의 신발 사랑 two", url: "/images/family/202310061200_son_장아련의 신발사랑_two.jpg"},
        { category: "album", title: "장아련의 신발 사랑", url: "/images/family/202310061200_son_장아련의 신발사랑.jpg"},
        { category: "album", title: "장하성가족과 증조 외할머니", url: "/images/family/202309271600_son_장하성 가족과 증조외할머니.JPG" },
        { category: "album", title: "작은할아버지와 장하성 가족", url: "/images/family/202309271700_son_작은할아버지와 장하성 가족.JPG" },
        { category: "album", title: "처음 포장 마차", url: "/images/family/202309271800_son_처음 포장마차.JPG" },
        { category: "album", title: "장하성의 피아노 사랑", url: "/images/family/2023092711_son_장하성의 피아노 사랑.jpeg" },
        { category: "album", title: "책을 좋아하는 장하성", url: "/images/family/202309261000_son_책을 사랑하는 장하성.JPG" },
        { category: "album", title: "강아지의 친구 하성츄츄", url: "/images/family/202309261001_son_강아지의 친구 하성츄츄.JPG" },
        { category: "album", title: "미미치치는 무섭다", url: "/images/family/202309231900__sister_무서운 누루하치.jpg" },
        { category: "album", title: "잠자는 숲속의 하성", url: "/images/family/202309251200_son_잠자는 숲속의 하성.jpg" },
        { category: "album", title: "르 카페에서의 가족들", url: "/images/family/2023092301_son_르 카페에서의 가족들.jpeg" },
        { category: "album", title: "어둠 속 용산 아파트 하성", url: "/images/family/2023092320_son_어둠속 용산아파트 하성.jpeg" },
        { category: "album", title: "엄마 닮은 하성", url: "/images/family/2023092210_son_엄마닮은 하성.JPG" },
        { category: "album", title: "장아련과 엄마츄츄", url: "/images/family/202309201000_son_장아련과 엄마츄츄.JPG" },
        { category: "album", title: "일어서는 장하성", url: "/images/family/2023091914_son_일어서는 장하성.jpeg" },
        { category: "album", title: "잠자는 거실의 하성", url: "/images/family/20230918_son_잠자는 거실의 하성.jpg" },
        { category: "album", title: "귀여운 강아지 루피", url: "/images/dog/2023091814_루피_강아지는 사랑입니다.jpeg" },
        { category: "album", title: "하성 친구의 세례식", url: "/images/family/2023091814_friend_하성 친구의 세례식.jpeg" },
        { category: "album", title: "역도선수하성", url: "/images/family/20230916_son_역도선수하성.JPG" },
        { category: "album", title: "애달픈 하성", url: "/images/family/2023091610_son_애달픈 하성.JPG" },
        { category: "album", title: "저는 인벤션을 칠 예정입니다.", url: "/images/family/2023091621_son_저는 인벤션을 칠 예정입니다.jpeg" },
        { category: "album", title: "엄마와 공부하는 하성", url: "/images/family/2023091510_son_의미심장한 엄마와 아들 놀이공부.jpg" },
        { category: "album", title: "요가 하성", url: "/images/family/2023090110_son_요가하성.jpg" },
        { category: "album", title: "아빠와 장하성 그리고 음악", url: "/images/family/2023091315_son_아빠와 장하성 그리고 음악.jpg" },
        { category: "album", title: "리모콘과 장또순", url: "/images/dog/2023091416_ddosun_리모콘과 장또순.jpg" },
        { category: "album", title: "할아버지발과 장또순", url: "/images/dog/2023091416_ddosun_아빠발과 장또순.jpg" },
        { category: "album", title: "키가 크는 농구선수", url: "/images/family/202309141045_son_속도감을 가진 장하성.JPG" },
        { category: "album", title: "얼음깨기를 좋아하다", url: "/images/family/20230913_son_아들_얼음깨기를 좋아하다.JPG" },
        { category: "album", title: "안방을 정리하는 아기", url: "/images/family/20230912_son_안방을 정리하는 아기.jpg" },
        { category: "album", title: "배드민턴 감독 장하성", url: "/images/family/20230911_son_배드민턴 감독.jpeg" },
        { category: "album", title: "장하성은 엄마를 좋아한다.", url: "/images/family/20230911_son_성남외고_행복한 세상의 장하성.jpeg" },
        { category: "album", title: "약사 장하성", url: "/images/family/20230908_son_약사_옷방_귀여움.jpeg" },
        { category: "album", title: "장하성과 엄마, DSLR", url: "/images/family/20230907_son_단란_가족_장하성.JPG" },
        { category: "album", title: "장하성과 엄마(23년8월28일)", url: "/images/family/20230828_son_장하성_엄마.jpg" },
        { category: "album", title: "장하성과 엄마(23년9월1일)", url: "/images/family/20230901_son_장하성_엄마.jpg" },
        { category: "album", title: "장하성의 리더십", url: "/images/family/20230905_son_아들_장하성_리더십.jpeg" },
        { category: "album", title: "아빠와 아기", url: "/images/family/20230905_son_아빠_아들_장하성.jpeg" },
        { category: "album", title: "늘 당당한 아기", url: "/images/family/20230903_thubnail_son_당당한_귀여운.JPG" },
        { category: "album", title: "아기부터 가지고 노는 모빌", url: "/images/family/20230903_son_귀여움_모빌.JPG" },
        { category: "album", title: "아빠와 장하성", url: "/images/family/20230902_son_배드민턴_아들_서울로.jpeg" },
        { category: "album", title: "연필을 잘 가지고 논다", url: "/images/family/20230824_son_호기심_책상_연필_작은방.jpeg" },
        { category: "album", title: "어리둥절한 하성 츄츄", url: "/images/family/20230813_son_어리둥절_엄마_화장실.jpeg" },
        { category: "album", title: "교회를 좋아하는 아이", url: "/images/family/20230813_son_교회.jpeg" },
        { category: "album", title: "버스 밖을 보며 잠을 달랜다", url: "/images/family/20230810_son_아련_제주도.png" },
        { category: "album", title: "엄마 품을 가장 좋아한다.", url: "/images/family/20230810_son_화이팅_커피업_엄마.jpeg" },
        { category: "album", title: "거울을 신기해 한다", url: "/images/family/20230811_son_호기심_작은방_거울.jpeg" },
        { category: "album", title: "웃음 엄마, 저녁", url: "/images/family/20230813_son_웃음_엄마_어딘가.jpeg" },
        { category: "album", title: "가평에서의 애기", url: "/images/family/20230822_son_무관심_가평_부엌.jpeg" },
        { category: "album", title: "텐트에서의 하성", url: "/images/family/20230822_son_의미심장_가평_텐트.jpeg" },
        { category: "album", title: "침대에서의 하성", url: "/images/family/20230824_son_웃음_침대_안방.jpeg" },
        { category: "album", title: "카트라이더 하성", url: "/images/family/2023083109_son_보행기_드래프트_호기심.jpeg" },
        { category: "album", title: "책 하성", url: "/images/family/202308291100_son_책_thefootbook_읽다.jpeg" },
        { category: "album", title: "귀염둥이 장또순 첫번째", url: "/images/dog/2021_귀염둥이 장또순 첫번째.jpeg" },
        { category: "album", title: "귀염둥이 장또순 두번째", url: "/images/dog/2021_귀염둥이 장또순 두번째.jpeg" },
        { category: "album", title: "귀염둥이 장또순 세번째", url: "/images/dog/2021_귀염둥이 장또순 세번째.jpeg" },

        { category: "youtube", title: "장용운의 유튜브", url: "https://www.youtube.com/@gyujanggak", thumbnail: "https://firebasestorage.googleapis.com/v0/b/gyujanggak-99e8a.appspot.com/o/gyujanggak%2Fprofile%2FjangNewProfile.png?alt=media&token=f11e6731-7b34-409b-9045-1181f256d705" },
        { category: "blog", title: "장용운의 블로그", url: "https://blog.naver.com/jyy3k", thumbnail: "https://firebasestorage.googleapis.com/v0/b/gyujanggak-99e8a.appspot.com/o/gyujanggak%2Fprofile%2Fyongwoonjang.png?alt=media&token=9c76d196-3b25-45a3-87ef-86acbdf8418e" },
        { category: "instagram", title: "장용운의 인스타그램", url: "https://www.instagram.com/j_major_scale/", thumbnail: "https://firebasestorage.googleapis.com/v0/b/gyujanggak-99e8a.appspot.com/o/gyujanggak%2Fprofile%2FYongwoonJangMediaCenter.png?alt=media&token=d63cc0cf-1567-4663-8afb-1086d856ed2f" },

        { category: "fun", title: "[Fun] 춤신", url: "https://youtube.com/clip/UgkxL0BZhNVc3kK-EA9j0MZ-suJi-O_CdyGr?feature=shared", thumbnail: "/images/funny/202309261100_fun_춤신.jpg" },
        { category: "fun", title: "[Fun] 춤신 two", url: "https://youtu.be/XApL1GElQqc?feature=shared", thumbnail: "/images/funny/202309261101_fun_춤신_two.jpg" }
    ]

export default function getDatabase(){
    return database;
}